classes:
  - cluster.virtual-mcp11-aio
parameters:
  _param:
    linux_system_codename: xenial
  linux:
    system:
      name: cfg01
      domain: ${_param:cluster_domain}
      purge_repos: ${_param:linux_system_purge_repos}
